# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python Byml_Dumper.py
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: Test Output
        path: |
          *.txt
    - shell: cmd
      if: github.ref == 'refs/heads/master'
      run: '7z a "${{ github.workspace }}/Model Name Dumper.zip" *.py -r Byml.cs Dumper Sarc.cs -xr!Source'
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Auto"
        prerelease: true
        title: "Auto Build"
        files: |
          *.zip
